name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"   # 2× za hodinu
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i --no-fund --no-audit

      # 1) skopíruj históriu do public/history.json (ak existuje v data/)
      - name: Build history (2022..today)
        run: npm run build:history

      # 2) vyrob čerstvý public/feed.json z TIPOS
      - name: Build feed.json (latest)
        env:
          SOURCE_URL: ${{ secrets.EJ_SOURCE_URL }}  # voliteľné prepísanie zdroja
        run: npm run build

      # 3) zlúč history + latest do public/feed.json
      - name: Merge history + latest
        run: npm run merge:history

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
