name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"   # 2× za hodinu
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      # (voliteľné) jednorazové/periodické dosypanie histórie zo seed skriptu
      # ak nemáš "build:history" script v package.json, tento blok môžeš vymazať
      - name: Build history (2022..today)
        continue-on-error: true
        run: npm run build:history

      # 1) Vygeneruj posledný žreb -> public/feed.json
      - name: Build feed.json
        env:
          SOURCE_URL: ${{ secrets.EJ_SOURCE_URL }}  # voliteľné pre prepísanie zdroja
        run: node fetch.js

      # 2) Inkrementálne aktualizuj public/history.json podľa public/feed.json
      - name: Update history.json
        run: node update_history.js

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
