 name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"   # 2× za hodinu
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      # 0) Online fetch -> public/feed.json (ak sa podarí)
      - name: Fetch latest online draw
        run: npm run fetch:online

      # Debug: čo priniesol fetch (nepadá, keď súbor nie je)
      - name: Show fetched feed (debug)
        run: |
          if [ -f public/feed.json ]; then
            echo "feed.json exists (from fetch:online)"
            head -n 60 public/feed.json || true
            node -e "const fs=require('fs');const p='public/feed.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));console.log('FETCHED LATEST DATE =', j?.draws?.[0]?.date)"
          else
            echo "feed.json MISSING after fetch:online (will try CSV fallback)"
          fi

      # 1) CSV fallback – SPUSTIŤ IBA AK feed.json NEEXISTUJE
      - name: Build feed.json (latest from CSV, fallback)
        if: ${{ hashFiles('public/feed.json') == '' }}
        run: npm run build:latest

      # 2) Postav históriu z CSV
      - name: Build history from CSV
        run: npm run build:history

      # 3) Spoj históriu + najnovší ťah (z fetchu alebo z CSV fallbacku)
      - name: Merge history + latest
        run: npm run merge:history

      # Diagnostika
      - name: List outputs
        run: ls -la public || true

      - name: Sanity check (print counts)
        run: |
          node -e "const fs=require('fs');const h='public/history.json';const f='public/feed.json';if(fs.existsSync(h)){const j=JSON.parse(fs.readFileSync(h,'utf8'));console.log('history drawCount=',j?.meta?.drawCount,' firstDate=',j?.draws?.[0]?.date);} else {console.log('history.json missing');process.exitCode=1;} if(fs.existsSync(f)){const k=JSON.parse(fs.readFileSync(f,'utf8'));console.log('feed latest date=',k?.draws?.[0]?.date);} else {console.log('feed.json missing');}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
