name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17 * * * *"   # každú hodinu v :17
  workflow_dispatch: {}

# tieto permissions sú potrebné pre Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Show env
        run: |
          node -v
          npm -v
          ls -la
          echo "----- package.json -----"
          cat package.json || true

      - name: Install deps
        run: |
          npm ci --no-audit --no-fund || npm install --no-audit --no-fund

      - name: Build feed (never fail job)
        run: |
          set -x
          mkdir -p public
          # spusti fetch.js – ak by zlyhal, nech job nepada
          node fetch.js || true
          # ak sa feed.json nevytvoril, sprav prázdny
          if [ ! -f public/feed.json ]; then
            echo '{ "meta": { "generatedAt": "'"$(date -Iseconds)"'", "nextJackpotEUR": null }, "draws": [] }' > public/feed.json
          fi
          # jednoduchá index stránka (nech je čo zobraziť)
          echo '<!doctype html><meta charset="utf-8"><title>Eurojackpot Feed</title><pre>' > public/index.html
          (command -v jq >/dev/null && jq . public/feed.json) || cat public/feed.json >> public/index.html
          echo '</pre>' >> public/index.html
          ls -la public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
