name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      - name: Build feed.json (latest)
        run: npm run build

      - name: Debug files before merge
        run: |
          echo "== ls public =="
          ls -la public || true
          echo "== feed.json =="
          cat public/feed.json || true
          echo "== history.json (before) =="
          cat public/history.json || true

      - name: Merge history + latest
        run: npm run merge:history

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
