name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"   # 2× za hodinu
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      # 1) najnovší ťah (feed.json)
      - name: Build feed.json (latest)
        run: npm run build:latest

      # 2) postav históriu z CSV (data/*.csv)
      - name: Build history from CSV
        run: npm run build:history

      # 3) spoj históriu + najnovší ťah -> public/history.json
      - name: Merge history + latest
        run: npm run merge:history

      - name: Sanity check (print counts)
        run: |
          node -e "const fs=require('fs'); const j=JSON.parse(fs.readFileSync('./public/history.json','utf8')); console.log('drawCount=', j?.meta?.drawCount, 'draws=', Array.isArray(j?.draws)? j.draws.length : 0);"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
