name: Update Eurojackpot feed

on:
  schedule:
    - cron: "17,47 * * * *"   # 2× za hodinu
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      # 0) Stiahni najnovší ťah z webu -> public/feed.json  (existujúci fetch.js v repo)
      - name: Fetch latest online (feed.json)
        run: node fetch.js

      # 1) Najnovší ťah z CSV (fallback) – nechajme, ale nie je nutné
      - name: Build feed.json (latest from CSV, fallback)
        run: npm run build:latest

      # 2) Prebehni cez CSV (history_*.csv) – môže byť no-op
      - name: Build history from CSV
        run: npm run build:history

      # 3) Spoj históriu + najnovší ťah z feedu -> public/history.json
      - name: Merge history + latest
        run: npm run merge:history

      # Diagnostika
      - name: List outputs
        run: ls -la public || true

      - name: Sanity check (print counts)
        run: |
          node -e "const fs=require('fs');const h='public/history.json';const f='public/feed.json';if(fs.existsSync(h)){const j=JSON.parse(fs.readFileSync(h,'utf8'));console.log('drawCount=',j?.meta?.drawCount,'draws=',Array.isArray(j?.draws)?j.draws.length:0);} else {console.log('history.json missing');process.exitCode=1;} if(fs.existsSync(f)){const k=JSON.parse(fs.readFileSync(f,'utf8'));console.log('feed latest date=',k?.draws?.[0]?.date);} else {console.log('feed.json missing');}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
